[msg Item_000]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_001]
[uf 0 5 65278][uf 2 1]A lightweight one-handed sword that's easy to handle.[n][e]

[msg Item_002]
[uf 0 5 65278][uf 2 1]A traditional Japanese sword. For [uf 4 2].[n][e]

[msg Item_003]
[uf 0 5 65278][uf 2 1]A curved, easy-to-use sword. For [uf 4 2].[n][e]

[msg Item_004]
[uf 0 5 65278][uf 2 1]A short sword designed for thrusting. For [uf 4 2].[n][e]

[msg Item_005]
[uf 0 5 65278][uf 2 1]A long sword said to have slayed ancient demons. For [uf 4 2].[n][e]

[msg Item_006]
[uf 0 5 65278][uf 2 1]An artistic, masterfully crafted shortsword. For [uf 4 2].[n][e]

[msg Item_007]
[uf 0 5 65278][uf 2 1]A sturdy, curved sword that can cut through iron. For [uf 4 2].[n][e]

[msg Item_008]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_009]
[uf 0 5 65278][uf 2 1]A Western sword with a silver blade. For [uf 4 2].[n][e]

[msg Item_00A]
[uf 0 5 65278][uf 2 1]A legendary knife known to few, but revered for its incredible cutting ability.[n][e]

[msg Item_00B]
[uf 0 5 65278][uf 2 1]A well-worn water pipe with a bit of a musty smell.[n][e]

[msg Item_00C]
[uf 0 5 65278][uf 2 1]A sturdy sword that emits spiritual energy. For [uf 4 2].[n][e]

[msg Item_00D]
[uf 0 5 65278][uf 2 1]A Western sword with a design inspired by a hero. For [uf 4 2].[n][e]

[msg Item_00E]
[uf 0 5 65278][uf 2 1]High likelihood to Repel physical attacks. For [uf 4 2].[n][e]

[msg Item_00F]
[uf 0 5 65278][uf 2 1]An elegant sword with moon-like decorations. For [uf 4 2].[n][e]

[msg Item_010]
[uf 0 5 65278][uf 2 1]A short sword made in the Heian period. For [uf 4 2].[n][e]

[msg Item_011]
[uf 0 5 65278][uf 2 1]A sharp sword with a reflective polish. For [uf 4 2].[n][e]

[msg Item_012]
[uf 0 5 65278][uf 2 1]A Japanese sword passed down by the Taira clan. For [uf 4 2].[n][e]

[msg Item_013]
[uf 0 5 65278][uf 2 1]A rugged sword blessed by the god of power. For [uf 4 2].[n][e]

[msg Item_014]
[uf 0 5 65278][uf 2 1]A ceremonial katana powered by the stars. For [uf 4 2].[n][e]

[msg Item_015]
[uf 0 5 65278][uf 2 1]A curved sword that seems to pulsate. For [uf 4 2].[n][e]

[msg Item_016]
[uf 0 5 65278][uf 2 1]A Western sword with a sharp tip. For [uf 4 2].[n][e]

[msg Item_017]
[uf 0 5 65278][uf 2 1]A holy sword favored by a knight-king of legend. For [uf 4 2].[n][e]

[msg Item_018]
[uf 0 5 65278][uf 2 1]A reddish-gold sword that cuts through resistances. For [uf 4 2].[n][e]

[msg Item_019]
[uf 0 5 65278][uf 2 1]A sword that strengthens magic attacks. For [uf 4 2].[n][e]

[msg Item_01A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_01B]
[uf 0 5 65278][uf 2 1]A fusion sword that is simple but well-forged. For [uf 4 2].[n][e]

[msg Item_01C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_01D]
[uf 0 5 65278][uf 2 1]A sword that changes attack affinity to Light. For [uf 4 2].[n][e]

[msg Item_01E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_01F]
[uf 0 5 65278][uf 2 1]A Western sword inhabited by spirits. For [uf 4 2].[n][e]

[msg Item_020]
[uf 0 5 65278][uf 2 1]A Western sword found inside a great tree. For [uf 4 2].[n][e]

[msg Item_021]
[uf 0 5 65278][uf 2 1]A long sword that is almost see-through. For [uf 4 2].[n][e]

[msg Item_022]
[uf 0 5 65278][uf 2 1]A short sword imbued with poisons. For [uf 4 2].[n][e]

[msg Item_023]
[uf 0 5 65278][uf 2 1]A short sword whose slash brings disaster. For [uf 4 2].[n][e]

[msg Item_024]
[uf 0 5 65278][uf 2 1]A longbow used for archery practice that is easy for beginners to use.[n][e]

[msg Item_025]
[uf 0 5 65278][uf 2 1]A lightweight short bow that is easy to handle. For Yukari.[n][e]

[msg Item_026]
[uf 0 5 65278][uf 2 1]A bow that emits an odd sound that confuses enemies. For Yukari.[n][e]

[msg Item_027]
[uf 0 5 65278][uf 2 1]A longbow wrapped tightly with rattan. For Yukari.[n][e]

[msg Item_028]
[uf 0 5 65278][uf 2 1]A fancy bow whose arrows leave a rainbow trail. For Yukari.[n][e]

[msg Item_029]
[uf 0 5 65278][uf 2 1]A longbow adorned with metallic ornaments. For Yukari.[n][e]

[msg Item_02A]
[uf 0 5 65278][uf 2 1]A short bow that is as light as a feather. For Yukari.[n][e]

[msg Item_02B]
[uf 0 5 65278][uf 2 1]A refined Japanese bow that shoots arrows in a beautiful arc. For Yukari.[n][e]

[msg Item_02C]
[uf 0 5 65278][uf 2 1]Shoots suction cup arrows. If it hits, it leaves a suction cup mark.[n][e]

[msg Item_02D]
[uf 0 5 65278][uf 2 1]A sturdy bow suited for long-range shooting. For Yukari.[n][e]

[msg Item_02E]
[uf 0 5 65278][uf 2 1]A hunting bow that shoots arrows covered in poison. For Yukari.[n][e]

[msg Item_02F]
[uf 0 5 65278][uf 2 1]A large bow that shakes the air with the snap of its string. For Yukari.[n][e]

[msg Item_030]
[uf 0 5 65278][uf 2 1]A Japanese bow that has been reinforced with bamboo. For Yukari.[n][e]

[msg Item_031]
[uf 0 5 65278][uf 2 1]A lightweight longbow blessed by the god of wind. For Yukari.[n][e]

[msg Item_032]
[uf 0 5 65278][uf 2 1]A short bow made of wood and animal hides. For Yukari.[n][e]

[msg Item_033]
[uf 0 5 65278][uf 2 1]A mystical bow enhanced by magical spells. For Yukari.[n][e]

[msg Item_034]
[uf 0 5 65278][uf 2 1]A large bow that produces powerful shots. For Yukari.[n][e]

[msg Item_035]
[uf 0 5 65278][uf 2 1]A longbow that shoots off arrows as fast as lightning. For Yukari.[n][e]

[msg Item_036]
[uf 0 5 65278][uf 2 1]A large, hefty bow that requires a lot of force to use. For Yukari.[n][e]

[msg Item_037]
[uf 0 5 65278][uf 2 1]A Japanese bow whose comfortable grip calms the user. For Yukari.[n][e]

[msg Item_038]
[uf 0 5 65278][uf 2 1]An exquisite bow that was used by a legendary archer. For Yukari.[n][e]

[msg Item_039]
[uf 0 5 65278][uf 2 1]A strong bow said to have been used by the god of destruction. For Yukari.[n][e]

[msg Item_03A]
[uf 0 5 65278][uf 2 1]A Japanese bow favored by a courageous leader. For Yukari.[n][e]

[msg Item_03B]
[uf 0 5 65278][uf 2 1]A winged bow that changes attack affinity to Light. For Yukari.[n][e]

[msg Item_03C]
[uf 0 5 65278][uf 2 1]A bow that strengthens the first magic attack of each battle. For Yukari.[n][e]

[msg Item_03D]
[uf 0 5 65278][uf 2 1]A fusion bow that easily hits enemies' weak points. For Yukari.[n][e]

[msg Item_03E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_03F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_040]
[uf 0 5 65278][uf 2 1]A massive bow that is hard to handle but powerful. For Yukari.[n][e]

[msg Item_041]
[uf 0 5 65278][uf 2 1]A Japanese bow in which the rage of a demonic spirit resides. For Yukari.[n][e]

[msg Item_042]
[uf 0 5 65278][uf 2 1]A magic bow that was favored by an ancient witch. For Yukari.[n][e]

[msg Item_043]
[uf 0 5 65278][uf 2 1]A bow that temporarily boosts Accuracy/Evasion. For Yukari.[n][e]

[msg Item_044]
[uf 0 5 65278][uf 2 1]A longbow that changes attack affinity to Wind. For Yukari.[n][e]

[msg Item_045]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_046]
[uf 0 5 65278][uf 2 1]A sinister bow that brings about disaster.[n]For Yukari.[n][e]

[msg Item_047]
[uf 0 5 65278][uf 2 1]A replica sword that looks real.[n][e]

[msg Item_048]
[uf 0 5 65278][uf 2 1]A two-handed sword that rouses the user's courage. For Junpei.[n][e]

[msg Item_049]
[uf 0 5 65278][uf 2 1]A great sword with exceeding length, weight, and strength. For Junpei.[n][e]

[msg Item_04A]
[uf 0 5 65278][uf 2 1]A heavy great sword used to crush opponents. For Junpei.[n][e]

[msg Item_04B]
[uf 0 5 65278][uf 2 1]A sword that can be drawn as fast as lightning. For Junpei.[n][e]

[msg Item_04C]
[uf 0 5 65278][uf 2 1]A long, two-handed sword. For Junpei.[n][e]

[msg Item_04D]
[uf 0 5 65278][uf 2 1]A lightweight sword that can be used in a variety of ways. For Junpei.[n][e]

[msg Item_04E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_04F]
[uf 0 5 65278][uf 2 1]A bat with nails driven into it. Release your inner bad boy.[n][e]

[msg Item_050]
[uf 0 5 65278][uf 2 1]A sword with a blade[n]like a lump of iron. For Junpei.[n][e]

[msg Item_051]
[uf 0 5 65278][uf 2 1]A two-handed sword that is lightweight but deadly. For Junpei.[n][e]

[msg Item_052]
[uf 0 5 65278][uf 2 1]A sword with a thick, heavy blade. For Junpei.[n][e]

[msg Item_053]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_054]
[uf 0 5 65278][uf 2 1]An unusually long two-handed sword. For Junpei.[n][e]

[msg Item_055]
[uf 0 5 65278][uf 2 1]A sword that temporarily boosts Defense. For Junpei.[n][e]

[msg Item_056]
[uf 0 5 65278][uf 2 1]A deadly katana with a strangely ominous aura. For Junpei.[n][e]

[msg Item_057]
[uf 0 5 65278][uf 2 1]A great sword that shines mystically. For Junpei.[n][e]

[msg Item_058]
[uf 0 5 65278][uf 2 1]A great sword that bears the name "Hard Lightning." For Junpei.[n][e]

[msg Item_059]
[uf 0 5 65278][uf 2 1]A sword that symbolizes turmoil. For Junpei.[n][e]

[msg Item_05A]
[uf 0 5 65278][uf 2 1]A sword that boasts strong cutting ability. For Junpei.[n][e]

[msg Item_05B]
[uf 0 5 65278][uf 2 1]A great sword made from the philosopher's stone. For Junpei.[n][e]

[msg Item_05C]
[uf 0 5 65278][uf 2 1]A sword made from the bones of poison snakes. For Junpei.[n][e]

[msg Item_05D]
[uf 0 5 65278][uf 2 1]A supreme magical sword that cuts through resistances. For Junpei.[n][e]

[msg Item_05E]
[uf 0 5 65278][uf 2 1]A massive sword that changes attack affinity to Fire. For Junpei.[n][e]

[msg Item_05F]
[uf 0 5 65278][uf 2 1]A dark red sword that doubles the user's critical rate. For Junpei.[n][e]

[msg Item_060]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_061]
[uf 0 5 65278][uf 2 1]A two-handed sword that strikes enemies with a heavy blow. For Junpei.[n][e]

[msg Item_062]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_063]
[uf 0 5 65278][uf 2 1]A sword favored by a monk who saved the country. For Junpei.[n][e]

[msg Item_064]
[uf 0 5 65278][uf 2 1]An especially sharp sword once used to decapitate a demon. For Junpei.[n][e]

[msg Item_065]
[uf 0 5 65278][uf 2 1]A great sword bearing the name of a crazed warrior. For Junpei.[n][e]

[msg Item_066]
[uf 0 5 65278][uf 2 1]A two-handed sword that reddens its victims. For Junpei.[n][e]

[msg Item_067]
[uf 0 5 65278][uf 2 1]A heated sword that changes attack affinity to Fire. For Junpei.[n][e]

[msg Item_068]
[uf 0 5 65278][uf 2 1]A sharp sword blessed by a dragon god. For Junpei.[n][e]

[msg Item_069]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_06A]
[uf 0 5 65278][uf 2 1]Weaponized gloves that are simple and easy to use.[n][e]

[msg Item_06B]
[uf 0 5 65278][uf 2 1]Gloves that were made from a powerful sword. For Sanada.[n][e]

[msg Item_06C]
[uf 0 5 65278][uf 2 1]Gloves designed to overwhelm enemies with speed. For Sanada.[n][e]

[msg Item_06D]
[uf 0 5 65278][uf 2 1]Weaponized gloves that double the user's critical rate. For Sanada.[n][e]

[msg Item_06E]
[uf 0 5 65278][uf 2 1]Weaponized gloves with spurs like beast fangs. For Sanada.[n][e]

[msg Item_06F]
[uf 0 5 65278][uf 2 1]Gloves that restore 1 HP upon death once per battle.[n][e]

[msg Item_070]
[uf 0 5 65278][uf 2 1]Cute gloves made to resemble the Jack brothers.[n][e]

[msg Item_071]
[uf 0 5 65278][uf 2 1]Weaponized gloves that strike with the power of a meteor. For Sanada.[n][e]

[msg Item_072]
[uf 0 5 65278][uf 2 1]Gloves that instill a strong spirit in the wearer. For Sanada.[n][e]

[msg Item_073]
[uf 0 5 65278][uf 2 1]Iron gloves that strengthen Strike attacks. For Sanada.[n][e]

[msg Item_074]
[uf 0 5 65278][uf 2 1]Weaponized gloves with sharp blades. For Sanada.[n][e]

[msg Item_075]
[uf 0 5 65278][uf 2 1]Magical gloves that suck the enemy's blood. For Sanada.[n][e]

[msg Item_076]
[uf 0 5 65278][uf 2 1]Weaponized gloves that unleash fierce power. For Sanada.[n][e]

[msg Item_077]
[uf 0 5 65278][uf 2 1]Gloves used by boxers. For Sanada.[n][e]

[msg Item_078]
[uf 0 5 65278][uf 2 1]Weaponized gloves that specialize in destructive power. For Sanada.[n][e]

[msg Item_079]
[uf 0 5 65278][uf 2 1]Weaponized gloves that are as light as air. For Sanada.[n][e]

[msg Item_07A]
[uf 0 5 65278][uf 2 1]Gloves made with[n]state-of-the-art technology. For Sanada.[n][e]

[msg Item_07B]
[uf 0 5 65278][uf 2 1]Weaponized gloves that are as hard as diamonds. For Sanada.[n][e]

[msg Item_07C]
[uf 0 5 65278][uf 2 1]Gloves that are the center of numerous legends. For Sanada.[n][e]

[msg Item_07D]
[uf 0 5 65278][uf 2 1]Weaponized gloves that temporarily boost the user's critical rate.[n][e]

[msg Item_07E]
[uf 0 5 65278][uf 2 1]Sacred gloves that make punches stronger. For Sanada.[n][e]

[msg Item_07F]
[uf 0 5 65278][uf 2 1]A mystic hand that changes attack affinity to Ice. For Sanada.[n][e]

[msg Item_080]
[uf 0 5 65278][uf 2 1]Magical gloves that temporarily boost all stats. For Sanada.[n][e]

[msg Item_081]
[uf 0 5 65278][uf 2 1]Fusion gloves suited for following up on previous attacks. For Sanada.[n][e]

[msg Item_082]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_083]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_084]
[uf 0 5 65278][uf 2 1]Ceremonial gloves used to pray with punches. For Sanada.[n][e]

[msg Item_085]
[uf 0 5 65278][uf 2 1]Gloves that house the soul of a fighter. For Sanada.[n][e]

[msg Item_086]
[uf 0 5 65278][uf 2 1]Lightweight gloves meant for executing swift combos. For Sanada.[n][e]

[msg Item_087]
[uf 0 5 65278][uf 2 1]Electrified gloves that change attack affinity to Electric. For Sanada.[n][e]

[msg Item_088]
[uf 0 5 65278][uf 2 1]Technical gloves that disrupt the opponent's pace. For Sanada.[n][e]

[msg Item_089]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_08D]
[uf 0 5 65278][uf 2 1]A sharp rapier designed for fighting Shadows.[n][e]

[msg Item_08E]
[uf 0 5 65278][uf 2 1]A short spear made for swift handling. For Mitsuru.[n][e]

[msg Item_08F]
[uf 0 5 65278][uf 2 1]A rapier that temporarily boosts Accuracy/Evasion. For Mitsuru.[n][e]

[msg Item_090]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_091]
[uf 0 5 65278][uf 2 1]A thrusting sword that changes attack affinity to Dark. For Mitsuru.[n][e]

[msg Item_092]
[uf 0 5 65278][uf 2 1]A thrusting sword that can be used for fencing. For Mitsuru.[n][e]

[msg Item_093]
[uf 0 5 65278][uf 2 1]A short spear that was used by a skilled warrior. For Mitsuru.[n][e]

[msg Item_094]
[uf 0 5 65278][uf 2 1]A demonic thrusting sword made solely to inflict pain. For Mitsuru.[n][e]

[msg Item_095]
[uf 0 5 65278][uf 2 1]A thrusting sword with a body curved like a snake. For Mitsuru.[n][e]

[msg Item_096]
[uf 0 5 65278][uf 2 1]An old-looking sword that emits a noise that sounds like singing. For Mitsuru.[n][e]

[msg Item_097]
[uf 0 5 65278][uf 2 1]A holy spear said to have repelled Satan. For Mitsuru.[n][e]

[msg Item_098]
[uf 0 5 65278][uf 2 1]A foreign rapier whose sting distresses enemies. For Mitsuru.[n][e]

[msg Item_099]
[uf 0 5 65278][uf 2 1]A thrusting sword befitting a noble. For Mitsuru.[n][e]

[msg Item_09A]
[uf 0 5 65278][uf 2 1]A short sword made for defense. For Mitsuru.[n][e]

[msg Item_09B]
[uf 0 5 65278][uf 2 1]A wavy sword that was used to kill a witch. For Mitsuru.[n][e]

[msg Item_09C]
[uf 0 5 65278][uf 2 1]A beautiful thrusting sword that smells of roses. For Mitsuru.[n][e]

[msg Item_09D]
[uf 0 5 65278][uf 2 1]A rapier that has been sharpened to the utmost. For Mitsuru.[n][e]

[msg Item_09E]
[uf 0 5 65278][uf 2 1]A divine spear that strengthens Ice attacks. For Mitsuru.[n][e]

[msg Item_09F]
[uf 0 5 65278][uf 2 1]An execution spear that temporarily boosts Attack. For Mitsuru.[n][e]

[msg Item_0A0]
[uf 0 5 65278][uf 2 1]A jet-black short spear that strengthens magic attacks. For Mitsuru.[n][e]

[msg Item_0A1]
[uf 0 5 65278][uf 2 1]A whip made of ice that changes attack affinity to Ice. For Mitsuru.[n][e]

[msg Item_0A2]
[uf 0 5 65278][uf 2 1]A cold thrusting sword said to glaciate enemies. For Mitsuru.[n][e]

[msg Item_0A3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0A8]
[uf 0 5 65278][uf 2 1]A saber that emits an icy chill. For Mitsuru.[n][e]

[msg Item_0A9]
[uf 0 5 65278][uf 2 1]A short spear that is elegant but deadly. For Mitsuru.[n][e]

[msg Item_0AA]
[uf 0 5 65278][uf 2 1]An eerie thrusting sword that emits a mysterious light. For Mitsuru.[n][e]

[msg Item_0AB]
[uf 0 5 65278][uf 2 1]A refined sword with a sophisticated aura. For Mitsuru.[n][e]

[msg Item_0AC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AD]
[uf 0 5 65278][uf 2 1]A sinister short spear that changes attack affinity to Dark. For Mitsuru.[n][e]

[msg Item_0AE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0AF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0B0]
[uf 0 5 65278][uf 2 1]A three-finger firing mechanism that uses the latest technologies.[n][e]

[msg Item_0B1]
[uf 0 5 65278][uf 2 1]A six-stage, automatic firing mechanism. For Aigis.[n][e]

[msg Item_0B2]
[uf 0 5 65278][uf 2 1]An 80mm caliber grenade launcher. For Aigis.[n][e]

[msg Item_0B3]
[uf 0 5 65278][uf 2 1]A rifle that fires bullets powered by orgone energy. For Aigis.[n][e]

[msg Item_0B4]
[uf 0 5 65278][uf 2 1]A cannon that fires off powerful blasts. For Aigis.[n][e]

[msg Item_0B5]
[uf 0 5 65278][uf 2 1]A cannon with a uniquely long barrel. For Aigis.[n][e]

[msg Item_0B6]
[uf 0 5 65278][uf 2 1]A firing mechanism that shoots poisonous bullets. For Aigis.[n][e]

[msg Item_0B7]
[uf 0 5 65278][uf 2 1]A cannon that uses electromagnetism to fire iron slugs. For Aigis.[n][e]

[msg Item_0B8]
[uf 0 5 65278][uf 2 1]A Vulcan cannon with an incredibly high rate of fire. For Aigis.[n][e]

[msg Item_0B9]
[uf 0 5 65278][uf 2 1]A weapon that fires iron fists, like something out of a robot anime.[n][e]

[msg Item_0BA]
[uf 0 5 65278][uf 2 1]The latest model of anti-Shadow rifle. For Aigis.[n][e]

[msg Item_0BB]
[uf 0 5 65278][uf 2 1]A firearm loaded with special rounds that bewilder foes. For Aigis.[n][e]

[msg Item_0BC]
[uf 0 5 65278][uf 2 1]A small but well-balanced rifle. For Aigis.[n][e]

[msg Item_0BD]
[uf 0 5 65278][uf 2 1]A firearm that is said to burn away impurity. For Aigis.[n][e]

[msg Item_0BE]
[uf 0 5 65278][uf 2 1]A cannon that generates annihilation between particles. For Aigis.[n][e]

[msg Item_0BF]
[uf 0 5 65278][uf 2 1]A sacred gun that reduces the HP cost of physical skills by half. For Aigis.[n][e]

[msg Item_0C0]
[uf 0 5 65278][uf 2 1]A grenade launcher that fires flash grenades. For Aigis.[n][e]

[msg Item_0C1]
[uf 0 5 65278][uf 2 1]A firearm with power like a kiss from a god. For Aigis.[n][e]

[msg Item_0C2]
[uf 0 5 65278][uf 2 1]A grenade launcher that launches icy grenades. For Aigis.[n][e]

[msg Item_0C3]
[uf 0 5 65278][uf 2 1]A firearm that shoots special rounds with high force of impact. For Aigis.[n][e]

[msg Item_0C4]
[uf 0 5 65278][uf 2 1]A robust firearm that shoots through resistances. For Aigis.[n][e]

[msg Item_0C5]
[uf 0 5 65278][uf 2 1]A fusion gun that has no quirks and is easy to use. For Aigis.[n][e]

[msg Item_0C6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0C8]
[uf 0 5 65278][uf 2 1]A gun that temporarily boosts Accuracy/Evasion of all allies. For Aigis.[n][e]

[msg Item_0C9]
[uf 0 5 65278][uf 2 1]A sharp knife designed for fighting Shadows.[n][e]

[msg Item_0CA]
[uf 0 5 65278][uf 2 1]A bone full of calcium that provides strength to those who chew it.[n][e]

[msg Item_0CB]
[uf 0 5 65278][uf 2 1]A well-polished kunai. For Koromaru.[n][e]

[msg Item_0CC]
[uf 0 5 65278][uf 2 1]A knife that is said to bring good fortune. For Koromaru.[n][e]

[msg Item_0CD]
[uf 0 5 65278][uf 2 1]A lethal blade shaped like a crescent moon. For Koromaru.[n][e]

[msg Item_0CE]
[uf 0 5 65278][uf 2 1]A kunai that was wielded by an assassin. For Koromaru.[n][e]

[msg Item_0CF]
[uf 0 5 65278][uf 2 1]A knife used to break swords. For Koromaru.[n][e]

[msg Item_0D0]
[uf 0 5 65278][uf 2 1]A pitch-black kunai that seems to reject light. For Koromaru.[n][e]

[msg Item_0D1]
[uf 0 5 65278][uf 2 1]A kunai that was favored by a certain ninja. For Koromaru.[n][e]

[msg Item_0D2]
[uf 0 5 65278][uf 2 1]A knife developed in a foreign country. For Koromaru.[n][e]

[msg Item_0D3]
[uf 0 5 65278][uf 2 1]A blade as powerful as a fierce howl. For Koromaru.[n][e]

[msg Item_0D4]
[uf 0 5 65278][uf 2 1]A thick, heavy knife. For Koromaru.[n][e]

[msg Item_0D5]
[uf 0 5 65278][uf 2 1]A kunai that strengthens Slash attacks. For Koromaru.[n][e]

[msg Item_0D6]
[uf 0 5 65278][uf 2 1]Raises Attack when on the receiving end of a Shift. For Koromaru.[n][e]

[msg Item_0D7]
[uf 0 5 65278][uf 2 1]A tool that halves the hit rate of incoming attacks. For Koromaru.[n][e]

[msg Item_0D8]
[uf 0 5 65278][uf 2 1]A fusion blade that strengthens Dark attacks. For Koromaru.[n][e]

[msg Item_0D9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0DB]
[uf 0 5 65278][uf 2 1]A knife that temporarily boosts Attack. For Koromaru.[n][e]

[msg Item_0DC]
[uf 0 5 65278][uf 2 1]A dagger that protects its user from misfortune. For Koromaru.[n][e]

[msg Item_0DD]
[uf 0 5 65278][uf 2 1]A knife polished so thoroughly that it shines. For Koromaru.[n][e]

[msg Item_0DE]
[uf 0 5 65278][uf 2 1]A kunai that changes attack affinity to Dark. For Koromaru.[n][e]

[msg Item_0DF]
[uf 0 5 65278][uf 2 1]A blade that changes attack affinity to Wind. For Koromaru.[n][e]

[msg Item_0E0]
[uf 0 5 65278][uf 2 1]A knife with thorough slicing ability. Should not be pointed at people.[n][e]

[msg Item_0E1]
[uf 0 5 65278][uf 2 1]A demonic knife that strengthens Dark attacks. For Koromaru.[n][e]

[msg Item_0E2]
[uf 0 5 65278][uf 2 1]An easy-to-use long spear designed for fighting Shadows.[n][e]

[msg Item_0E3]
[uf 0 5 65278][uf 2 1]A magical spear that temporarily boosts Attack. For Amada.[n][e]

[msg Item_0E4]
[uf 0 5 65278][uf 2 1]A long-handled weapon used during Europe's middle ages. For Amada.[n][e]

[msg Item_0E5]
[uf 0 5 65278][uf 2 1]A long spear with a beautifully-shaped head. For Amada.[n][e]

[msg Item_0E6]
[uf 0 5 65278][uf 2 1]A long spear that was used by a legendary king. For Amada.[n][e]

[msg Item_0E7]
[uf 0 5 65278][uf 2 1]A sinister spear that is said to call forth death. For Amada.[n][e]

[msg Item_0E8]
[uf 0 5 65278][uf 2 1]A common brush used for cleaning. Can also clean the area of Shadows.[n][e]

[msg Item_0E9]
[uf 0 5 65278][uf 2 1]A long spear with superb piercing power. For Amada.[n][e]

[msg Item_0EA]
[uf 0 5 65278][uf 2 1]A cross-shaped spear with fearsome cutting ability. For Amada.[n][e]

[msg Item_0EB]
[uf 0 5 65278][uf 2 1]A renowned spear that is long and beautiful. For Amada.[n][e]

[msg Item_0EC]
[uf 0 5 65278][uf 2 1]A long-handled weapon with a simple shape. For Amada.[n][e]

[msg Item_0ED]
[uf 0 5 65278][uf 2 1]A long-handled weapon dipped in poison. For Amada.[n][e]

[msg Item_0EE]
[uf 0 5 65278][uf 2 1]A long spear made in the Muromachi period. For Amada.[n][e]

[msg Item_0EF]
[uf 0 5 65278][uf 2 1]A long spear that was favored by an ancient emperor. For Amada.[n][e]

[msg Item_0F0]
[uf 0 5 65278][uf 2 1]A spear that protects the user from mental ailments. For Amada.[n][e]

[msg Item_0F1]
[uf 0 5 65278][uf 2 1]A magical spear that changes attack affinity to Light. For Amada.[n][e]

[msg Item_0F2]
[uf 0 5 65278][uf 2 1]A silver spear that changes attack affinity to Electric. For Amada.[n][e]

[msg Item_0F3]
[uf 0 5 65278][uf 2 1]A trident imbued with the power of destruction and creation. For Amada.[n][e]

[msg Item_0F4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_0F7]
[uf 0 5 65278][uf 2 1]A cross-shaped spear said to have belonged to royalty. For Amada.[n][e]

[msg Item_0F8]
[uf 0 5 65278][uf 2 1]A special spear that is constantly surging with electricity. For Amada.[n][e]

[msg Item_0F9]
[uf 0 5 65278][uf 2 1]A mystical spear that grants its user magical powers. For Amada.[n][e]

[msg Item_0FA]
[uf 0 5 65278][uf 2 1]A ceremonial lance that changes attack affinity to Light. For Amada.[n][e]

[msg Item_0FB]
[uf 0 5 65278][uf 2 1]A destructive battle-axe designed for fighting Shadows.[n][e]

[msg Item_0FC]
[uf 0 5 65278][uf 2 1]A giant hammer that emits a ferocious aura. For Aragaki.[n][e]

[msg Item_0FD]
[uf 0 5 65278][uf 2 1]A dangerous cudgel made by a psychopathic murderer. For Aragaki.[n][e]

[msg Item_0FE]
[uf 0 5 65278][uf 2 1]It says, "Front of School." It should probably be returned someday.[n][e]

[msg Item_0FF]
[uf 0 5 65278][uf 2 1]A giant axe that was used for executions. For Aragaki.[n][e]

[msg Item_100]
[uf 0 5 65278][uf 2 1]A rod that boasts significant strength. For Aragaki.[n][e]

[msg Item_101]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_102]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_103]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_104]
[uf 0 5 65278][uf 2 1]Temporarily boosts the user's critical rate. For Aragaki.[n][e]

[msg Item_105]
[uf 0 5 65278][uf 2 1]A giant hammer blessed by the god of earth. For Aragaki.[n][e]

[msg Item_106]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_107]
[uf 0 5 65278][uf 2 1]A battle-axe that strengthens Strike attacks. For Aragaki.[n][e]

[msg Item_108]
[uf 0 5 65278][uf 2 1]A large, metal hammer that can shatter the ground. For Aragaki.[n][e]

[msg Item_109]
[uf 0 5 65278][uf 2 1]A sacred hammer that changes attack affinity to Electric. For Aragaki.[n][e]

[msg Item_10A]
[uf 0 5 65278][uf 2 1]A staff that strengthens the first physical attack of each battle. For Aragaki.[n][e]

[msg Item_10B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_10C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_10D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_10E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_10F]
[uf 0 5 65278][uf 2 1]User recovers SP when on the receiving end of a Shift. For Amada.[n][e]

[msg Item_110]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_111]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_112]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_113]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_114]
[uf 0 5 65278][uf 2 1]Nothing is equipped.[n][e]

[msg Item_115]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_116]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_117]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_118]
[uf 0 5 65278][uf 2 1]A sharp one-handed sword designed for fighting Shadows.[n][e]

[msg Item_119]
[uf 0 5 65278][uf 2 1]A powerful longbow designed for fighting Shadows.[n][e]

[msg Item_11A]
[uf 0 5 65278][uf 2 1]A long, heavy great sword designed for fighting Shadows.[n][e]

[msg Item_11B]
[uf 0 5 65278][uf 2 1]Tough weaponized gloves designed for fighting Shadows.[n][e]

[msg Item_11C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_11D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_11E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_11F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_120]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_121]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_122]
[uf 0 5 65278][uf 2 1]A sword that changes attack affinity to Dark. For [uf 4 2].[n][e]

[msg Item_123]
[uf 0 5 65278][uf 2 1]This sword of legend... is a fake. The anger of being tricked turns into power.[n][e]

[msg Item_124]
[uf 0 5 65278][uf 2 1]Medium likelihood to Repel physical attacks. For [uf 4 2].[n][e]

[msg Item_125]
[uf 0 5 65278][uf 2 1]A cursed sword seeped in blood. For [uf 4 2].[n][e]

[msg Item_126]
[uf 0 5 65278][uf 2 1]A sword that changes attack affinity to Light. For [uf 4 2].[n][e]

[msg Item_127]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_128]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_129]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_12F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_130]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_131]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_132]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_133]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_134]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_135]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_136]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_137]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_138]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_139]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_13F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_140]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_141]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_142]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_143]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_144]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_145]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_146]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_147]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_148]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_149]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_14F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_150]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_151]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_152]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_153]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_154]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_155]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_156]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_157]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_158]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_159]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_15F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_160]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_161]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_162]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_163]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_164]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_165]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_166]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_167]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_168]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_169]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_16F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_170]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_171]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_172]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_173]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_174]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_175]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_176]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_177]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_178]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_179]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_17F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_180]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_181]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_182]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_183]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_184]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_185]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_186]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_187]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_188]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_189]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_18F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_190]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_191]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_192]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_193]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_194]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_195]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_196]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_197]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_198]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_199]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19A]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19B]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19C]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19D]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19E]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_19F]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1A9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1AF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1B9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1BF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1C9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1CF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1D9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1DF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1E9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1ED]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1EF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F0]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F1]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F2]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F3]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F4]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F5]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F6]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F7]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F8]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1F9]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FA]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FB]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FC]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FD]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FE]
[uf 0 5 65278][uf 2 1]未使用[n][e]

[msg Item_1FF]
[uf 0 5 65278][uf 2 1]未使用[n][e]

