name: Your Weapon Name
base:
  mesh_path: #[OPTIONAL] Path to base weapon skeleton
  anim_path: #[OPTIONAL] Path to weapon animations? If they have anims?
mesh:
  mesh_path: #[OPTIONAL] Path to weapon mesh not in the weapon folder
stats:
  attr_id: 0 #Damage attribute SEE NOTES
  rarity: 1 #[OPTIONAL]
  tier: 1 #[OPTIONAL]
  attack: 30 #Damage output
  accuracy: 95 #Accuracy modifier
  strength: 0 #[OPTIONAL]
  magic: 0 #[OPTIONAL]
  endurance: 0 #[OPTIONAL]
  agility: 0 #[OPTIONAL]
  luck: 0 #[OPTIONAL]
  skill_id: 0 #[OPTIONAL]
  price: 400 #[OPTIONAL]
  sell_price: 100 #[OPTIONAL]

#NOTES
    #Anything marked [OPTIONAL] is not needed and will fall back to a default value
    
    #RE: DAMAGE ATTRIBUTES
    #The possible attributes are as follows
        #PHYSICAL 
            #0 = Slash
            #1 = Strike 
            #2 = Pierce
        #ELEMENTAL
            #3 = Fire
            #4 = Ice
            #5 = Electric
            #6 = Wind
            #7 = Almighty
            #8 = Light/Bless
            #9 = Dark/Curse
    #Do not go any higher