[msg Item_000]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_001]
[f 0 5 65278][f 2 1]A lightweight one-handed sword that's easy to handle.[n][e]

[msg Item_002]
[f 0 5 65278][f 2 1]A traditional Japanese sword. For [f 4 2].[n][e]

[msg Item_003]
[f 0 5 65278][f 2 1]A curved, easy-to-use sword. For [f 4 2].[n][e]

[msg Item_004]
[f 0 5 65278][f 2 1]A short sword designed for thrusting. For [f 4 2].[n][e]

[msg Item_005]
[f 0 5 65278][f 2 1]A long sword said to have slayed ancient demons. For [f 4 2].[n][e]

[msg Item_006]
[f 0 5 65278][f 2 1]An artistic, masterfully crafted shortsword. For [f 4 2].[n][e]

[msg Item_007]
[f 0 5 65278][f 2 1]A sturdy, curved sword that can cut through iron. For [f 4 2].[n][e]

[msg Item_008]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_009]
[f 0 5 65278][f 2 1]A Western sword with a silver blade. For [f 4 2].[n][e]

[msg Item_00A]
[f 0 5 65278][f 2 1]A legendary knife known to few, but revered for its incredible cutting ability.[n][e]

[msg Item_00B]
[f 0 5 65278][f 2 1]A well-worn water pipe with a bit of a musty smell.[n][e]

[msg Item_00C]
[f 0 5 65278][f 2 1]A sturdy sword that emits spiritual energy. For [f 4 2].[n][e]

[msg Item_00D]
[f 0 5 65278][f 2 1]A Western sword with a design inspired by a hero. For [f 4 2].[n][e]

[msg Item_00E]
[f 0 5 65278][f 2 1]High likelihood to Repel physical attacks. For [f 4 2].[n][e]

[msg Item_00F]
[f 0 5 65278][f 2 1]An elegant sword with moon-like decorations. For [f 4 2].[n][e]

[msg Item_010]
[f 0 5 65278][f 2 1]A short sword made in the Heian period. For [f 4 2].[n][e]

[msg Item_011]
[f 0 5 65278][f 2 1]A sharp sword with a reflective polish. For [f 4 2].[n][e]

[msg Item_012]
[f 0 5 65278][f 2 1]A Japanese sword passed down by the Taira clan. For [f 4 2].[n][e]

[msg Item_013]
[f 0 5 65278][f 2 1]A rugged sword blessed by the god of power. For [f 4 2].[n][e]

[msg Item_014]
[f 0 5 65278][f 2 1]A ceremonial katana powered by the stars. For [f 4 2].[n][e]

[msg Item_015]
[f 0 5 65278][f 2 1]A curved sword that seems to pulsate. For [f 4 2].[n][e]

[msg Item_016]
[f 0 5 65278][f 2 1]A Western sword with a sharp tip. For [f 4 2].[n][e]

[msg Item_017]
[f 0 5 65278][f 2 1]A holy sword favored by a knight-king of legend. For [f 4 2].[n][e]

[msg Item_018]
[f 0 5 65278][f 2 1]A reddish-gold sword that cuts through resistances. For [f 4 2].[n][e]

[msg Item_019]
[f 0 5 65278][f 2 1]A sword that strengthens magic attacks. For [f 4 2].[n][e]

[msg Item_01A]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_01B]
[f 0 5 65278][f 2 1]A fusion sword that is simple but well-forged. For [f 4 2].[n][e]

[msg Item_01C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_01D]
[f 0 5 65278][f 2 1]A sword that changes attack affinity to Light. For [f 4 2].[n][e]

[msg Item_01E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_01F]
[f 0 5 65278][f 2 1]A Western sword inhabited by spirits. For [f 4 2].[n][e]

[msg Item_020]
[f 0 5 65278][f 2 1]A Western sword found inside a great tree. For [f 4 2].[n][e]

[msg Item_021]
[f 0 5 65278][f 2 1]A long sword that is almost see-through. For [f 4 2].[n][e]

[msg Item_022]
[f 0 5 65278][f 2 1]A short sword imbued with poisons. For [f 4 2].[n][e]

[msg Item_023]
[f 0 5 65278][f 2 1]A short sword whose slash brings disaster. For [f 4 2].[n][e]

[msg Item_024]
[f 0 5 65278][f 2 1]A longbow used for archery practice that is easy for beginners to use.[n][e]

[msg Item_025]
[f 0 5 65278][f 2 1]A lightweight short bow that is easy to handle. For Yukari.[n][e]

[msg Item_026]
[f 0 5 65278][f 2 1]A bow that emits an odd sound that confuses enemies. For Yukari.[n][e]

[msg Item_027]
[f 0 5 65278][f 2 1]A longbow wrapped tightly with rattan. For Yukari.[n][e]

[msg Item_028]
[f 0 5 65278][f 2 1]A fancy bow whose arrows leave a rainbow trail. For Yukari.[n][e]

[msg Item_029]
[f 0 5 65278][f 2 1]A longbow adorned with metallic ornaments. For Yukari.[n][e]

[msg Item_02A]
[f 0 5 65278][f 2 1]A short bow that is as light as a feather. For Yukari.[n][e]

[msg Item_02B]
[f 0 5 65278][f 2 1]A refined Japanese bow that shoots arrows in a beautiful arc. For Yukari.[n][e]

[msg Item_02C]
[f 0 5 65278][f 2 1]Shoots suction cup arrows. If it hits, it leaves a suction cup mark.[n][e]

[msg Item_02D]
[f 0 5 65278][f 2 1]A sturdy bow suited for long-range shooting. For Yukari.[n][e]

[msg Item_02E]
[f 0 5 65278][f 2 1]A hunting bow that shoots arrows covered in poison. For Yukari.[n][e]

[msg Item_02F]
[f 0 5 65278][f 2 1]A large bow that shakes the air with the snap of its string. For Yukari.[n][e]

[msg Item_030]
[f 0 5 65278][f 2 1]A Japanese bow that has been reinforced with bamboo. For Yukari.[n][e]

[msg Item_031]
[f 0 5 65278][f 2 1]A bow infused with the essence of fallen tears. For Yukari.[n][e]

[msg Item_032]
[f 0 5 65278][f 2 1]A short bow made of wood and animal hides. For Yukari.[n][e]

[msg Item_033]
[f 0 5 65278][f 2 1]A bow that embodies the sigh of a sinner, head hung low. For Yukari.[n][e]

[msg Item_034]
[f 0 5 65278][f 2 1]A large bow that produces powerful shots. For Yukari.[n][e]

[msg Item_035]
[f 0 5 65278][f 2 1]A bow harboring the rage of one who fell into madness. For Yukari.[n][e]

[msg Item_036]
[f 0 5 65278][f 2 1]A large, hefty bow that requires a lot of force to use. For Yukari.[n][e]

[msg Item_037]
[f 0 5 65278][f 2 1]A bow made of frozen tears. For Yukari.[n][e]

[msg Item_038]
[f 0 5 65278][f 2 1]An exquisite bow that was used by a legendary archer. For Yukari.[n][e]

[msg Item_039]
[f 0 5 65278][f 2 1]A bow of beautiful and radiant power. For Yukari.[n][e]

[msg Item_03A]
[f 0 5 65278][f 2 1]A Japanese bow favored by a courageous leader. For Yukari.[n][e]

[msg Item_03B]
[f 0 5 65278][f 2 1]A winged bow that changes attack affinity to Light. For Yukari.[n][e]

[msg Item_03C]
[f 0 5 65278][f 2 1]A bow that strengthens the first magic attack of each battle. For Yukari.[n][e]

[msg Item_03D]
[f 0 5 65278][f 2 1]A fusion bow that easily hits enemies' weak points. For Yukari.[n][e]

[msg Item_03E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_03F]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_040]
[f 0 5 65278][f 2 1]A massive bow that is hard to handle but powerful. For Yukari.[n][e]

[msg Item_041]
[f 0 5 65278][f 2 1]A bow of twisted and distorted power. For Yukari.[n][e]

[msg Item_042]
[f 0 5 65278][f 2 1]A magic bow that was favored by an ancient witch. For Yukari.[n][e]

[msg Item_043]
[f 0 5 65278][f 2 1]A bow that temporarily boosts Accuracy/Evasion. For Yukari.[n][e]

[msg Item_044]
[f 0 5 65278][f 2 1]A longbow that changes attack affinity to Wind. For Yukari.[n][e]

[msg Item_045]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_046]
[f 0 5 65278][f 2 1]A sinister bow that brings about disaster. For Yukari.[n][e]

[msg Item_047]
[f 0 5 65278][f 2 1]A replica sword that looks real.[n][e]

[msg Item_048]
[f 0 5 65278][f 2 1]A two-handed sword that rouses the user's courage. For Junpei.[n][e]

[msg Item_049]
[f 0 5 65278][f 2 1]A great sword with exceeding length, weight, and strength. For Junpei.[n][e]

[msg Item_04A]
[f 0 5 65278][f 2 1]A heavy great sword used to crush opponents. For Junpei.[n][e]

[msg Item_04B]
[f 0 5 65278][f 2 1]A sword that can be drawn as fast as lightning. For Junpei.[n][e]

[msg Item_04C]
[f 0 5 65278][f 2 1]A sword infused with the essence of fallen tears. For Junpei.[n][e]

[msg Item_04D]
[f 0 5 65278][f 2 1]A lightweight sword that can be used in a variety of ways. For Junpei.[n][e]

[msg Item_04E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_04F]
[f 0 5 65278][f 2 1]A bat with nails driven into it. Release your inner bad boy.[n][e]

[msg Item_050]
[f 0 5 65278][f 2 1]A sword with a blade[n]like a lump of iron. For Junpei.[n][e]

[msg Item_051]
[f 0 5 65278][f 2 1]A two-handed sword that is lightweight but deadly. For Junpei.[n][e]

[msg Item_052]
[f 0 5 65278][f 2 1]A sword with a thick, heavy blade. For Junpei.[n][e]

[msg Item_053]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_054]
[f 0 5 65278][f 2 1]An unusually long two-handed sword. For Junpei.[n][e]

[msg Item_055]
[f 0 5 65278][f 2 1]A sword that temporarily boosts Defense. For Junpei.[n][e]

[msg Item_056]
[f 0 5 65278][f 2 1]A deadly katana with a strangely ominous aura. For Junpei.[n][e]

[msg Item_057]
[f 0 5 65278][f 2 1]A sword harboring the rage of one who fell into madness. For Junpei.[n][e]

[msg Item_058]
[f 0 5 65278][f 2 1]A great sword that bears the name "Hard Lightning." For Junpei.[n][e]

[msg Item_059]
[f 0 5 65278][f 2 1]A sword made of frozen tears. For Junpei.[n][e]

[msg Item_05A]
[f 0 5 65278][f 2 1]A sword that boasts strong cutting ability. For Junpei.[n][e]

[msg Item_05B]
[f 0 5 65278][f 2 1]A sword of beautiful and radiant power. For Junpei.[n][e]

[msg Item_05C]
[f 0 5 65278][f 2 1]A sword that embodies the sigh of a sinner, head hung low. For Junpei.[n][e]

[msg Item_05D]
[f 0 5 65278][f 2 1]A supreme magical sword that cuts through resistances. For Junpei.[n][e]

[msg Item_05E]
[f 0 5 65278][f 2 1]A massive sword that changes attack affinity to Fire. For Junpei.[n][e]

[msg Item_05F]
[f 0 5 65278][f 2 1]A dark red sword that doubles the user's critical rate. For Junpei.[n][e]

[msg Item_060]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_061]
[f 0 5 65278][f 2 1]A two-handed sword that strikes enemies with a heavy blow. For Junpei.[n][e]

[msg Item_062]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_063]
[f 0 5 65278][f 2 1]A sword favored by a monk who saved the country. For Junpei.[n][e]

[msg Item_064]
[f 0 5 65278][f 2 1]An especially sharp sword once used to decapitate a demon. For Junpei.[n][e]

[msg Item_065]
[f 0 5 65278][f 2 1]A great sword bearing the name of a crazed warrior. For Junpei.[n][e]

[msg Item_066]
[f 0 5 65278][f 2 1]A sword of twisted and distorted power. For Junpei.[n][e]

[msg Item_067]
[f 0 5 65278][f 2 1]A heated sword that changes attack affinity to Fire. For Junpei.[n][e]

[msg Item_068]
[f 0 5 65278][f 2 1]A sharp sword blessed by a dragon god. For Junpei.[n][e]

[msg Item_069]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_06A]
[f 0 5 65278][f 2 1]Weaponized gloves that are simple and easy to use.[n][e]

[msg Item_06B]
[f 0 5 65278][f 2 1]Gloves that were made from a powerful sword. For Sanada.[n][e]

[msg Item_06C]
[f 0 5 65278][f 2 1]Gloves designed to overwhelm enemies with speed. For Sanada.[n][e]

[msg Item_06D]
[f 0 5 65278][f 2 1]Weaponized gloves that double the user's critical rate. For Sanada.[n][e]

[msg Item_06E]
[f 0 5 65278][f 2 1]Weaponized gloves with spurs like beast fangs. For Sanada.[n][e]

[msg Item_06F]
[f 0 5 65278][f 2 1]Gloves that restore 1 HP upon death once per battle.[n][e]

[msg Item_070]
[f 0 5 65278][f 2 1]Cute gloves made to resemble the Jack brothers.[n][e]

[msg Item_071]
[f 0 5 65278][f 2 1]Weaponized gloves that strike with the power of a meteor. For Sanada.[n][e]

[msg Item_072]
[f 0 5 65278][f 2 1]Gloves that instill a strong spirit in the wearer. For Sanada.[n][e]

[msg Item_073]
[f 0 5 65278][f 2 1]Iron gloves that strengthen Strike attacks. For Sanada.[n][e]

[msg Item_074]
[f 0 5 65278][f 2 1]Weaponized gloves with sharp blades. For Sanada.[n][e]

[msg Item_075]
[f 0 5 65278][f 2 1]Gloves infused with the essence of fallen tears. For Sanada.[n][e]

[msg Item_076]
[f 0 5 65278][f 2 1]Weaponized gloves that unleash fierce power. For Sanada.[n][e]

[msg Item_077]
[f 0 5 65278][f 2 1]Gloves that embody the sigh of a sinner, head hung low. For Sanada.[n][e]

[msg Item_078]
[f 0 5 65278][f 2 1]Weaponized gloves that specialize in destructive power. For Sanada.[n][e]

[msg Item_079]
[f 0 5 65278][f 2 1]Gloves harboring the rage of one who fell into madness. For Sanada.[n][e]

[msg Item_07A]
[f 0 5 65278][f 2 1]Gloves made with[n]state-of-the-art technology. For Sanada.[n][e]

[msg Item_07B]
[f 0 5 65278][f 2 1]Gloves made of frozen tears. For Sanada.[n][e]

[msg Item_07C]
[f 0 5 65278][f 2 1]Gloves that are the center of numerous legends. For Sanada.[n][e]

[msg Item_07D]
[f 0 5 65278][f 2 1]Gloves of beautiful and radiant power. For Sanada.[n][e]

[msg Item_07E]
[f 0 5 65278][f 2 1]Sacred gloves that make punches stronger. For Sanada.[n][e]

[msg Item_07F]
[f 0 5 65278][f 2 1]A mystic hand that changes attack affinity to Ice. For Sanada.[n][e]

[msg Item_080]
[f 0 5 65278][f 2 1]Magical gloves that temporarily boost all stats. For Sanada.[n][e]

[msg Item_081]
[f 0 5 65278][f 2 1]Fusion gloves suited for following up on previous attacks. For Sanada.[n][e]

[msg Item_082]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_083]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_084]
[f 0 5 65278][f 2 1]Ceremonial gloves used to pray with punches. For Sanada.[n][e]

[msg Item_085]
[f 0 5 65278][f 2 1]Gloves of twisted and distorted power. For Sanada.[n][e]

[msg Item_086]
[f 0 5 65278][f 2 1]Lightweight gloves meant for executing swift combos. For Sanada.[n][e]

[msg Item_087]
[f 0 5 65278][f 2 1]Electrified gloves that change attack affinity to Electric. For Sanada.[n][e]

[msg Item_088]
[f 0 5 65278][f 2 1]Technical gloves that disrupt the opponent's pace. For Sanada.[n][e]

[msg Item_089]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_08A]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_08B]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_08C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_08D]
[f 0 5 65278][f 2 1]A sharp rapier designed for fighting Shadows.[n][e]

[msg Item_08E]
[f 0 5 65278][f 2 1]A short spear made for swift handling. For Mitsuru.[n][e]

[msg Item_08F]
[f 0 5 65278][f 2 1]A rapier that temporarily boosts Accuracy/Evasion. For Mitsuru.[n][e]

[msg Item_090]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_091]
[f 0 5 65278][f 2 1]A thrusting sword that changes attack affinity to Dark. For Mitsuru.[n][e]

[msg Item_092]
[f 0 5 65278][f 2 1]A rapier that embodies the sigh of a sinner, head hung low. For Mitsuru.[n][e]

[msg Item_093]
[f 0 5 65278][f 2 1]A short spear that was used by a skilled warrior. For Mitsuru.[n][e]

[msg Item_094]
[f 0 5 65278][f 2 1]A demonic thrusting sword made solely to inflict pain. For Mitsuru.[n][e]

[msg Item_095]
[f 0 5 65278][f 2 1]A thrusting sword with a body curved like a snake. For Mitsuru.[n][e]

[msg Item_096]
[f 0 5 65278][f 2 1]A rapier infused with the essence of fallen tears. For Mitsuru.[n][e]

[msg Item_097]
[f 0 5 65278][f 2 1]A holy spear said to have repelled Satan. For Mitsuru.[n][e]

[msg Item_098]
[f 0 5 65278][f 2 1]A rapier of twisted and distorted power. For Mitsuru.[n][e]

[msg Item_099]
[f 0 5 65278][f 2 1]A thrusting sword befitting a noble. For Mitsuru.[n][e]

[msg Item_09A]
[f 0 5 65278][f 2 1]A rapier harboring the rage of one who fell into madness. For Mitsuru.[n][e]

[msg Item_09B]
[f 0 5 65278][f 2 1]A rapier made of frozen tears. For Mitsuru.[n][e]

[msg Item_09C]
[f 0 5 65278][f 2 1]A beautiful thrusting sword that smells of roses. For Mitsuru.[n][e]

[msg Item_09D]
[f 0 5 65278][f 2 1]A rapier that has been sharpened to the utmost. For Mitsuru.[n][e]

[msg Item_09E]
[f 0 5 65278][f 2 1]A divine spear that strengthens Ice attacks. For Mitsuru.[n][e]

[msg Item_09F]
[f 0 5 65278][f 2 1]An execution spear that temporarily boosts Attack. For Mitsuru.[n][e]

[msg Item_0A0]
[f 0 5 65278][f 2 1]A jet-black short spear that strengthens magic attacks. For Mitsuru.[n][e]

[msg Item_0A1]
[f 0 5 65278][f 2 1]A whip made of ice that changes attack affinity to Ice. For Mitsuru.[n][e]

[msg Item_0A2]
[f 0 5 65278][f 2 1]A cold thrusting sword said to glaciate enemies. For Mitsuru.[n][e]

[msg Item_0A3]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0A4]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0A5]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0A6]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0A7]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0A8]
[f 0 5 65278][f 2 1]A saber that emits an icy chill. For Mitsuru.[n][e]

[msg Item_0A9]
[f 0 5 65278][f 2 1]A short spear that is elegant but deadly. For Mitsuru.[n][e]

[msg Item_0AA]
[f 0 5 65278][f 2 1]A rapier of beautiful and radiant power. For Mitsuru.[n][e]

[msg Item_0AB]
[f 0 5 65278][f 2 1]A refined sword with a sophisticated aura. For Mitsuru.[n][e]

[msg Item_0AC]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0AD]
[f 0 5 65278][f 2 1]A sinister short spear that changes attack affinity to Dark. For Mitsuru.[n][e]

[msg Item_0AE]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0AF]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0B0]
[f 0 5 65278][f 2 1]A three-finger firing mechanism that uses the latest technologies.[n][e]

[msg Item_0B1]
[f 0 5 65278][f 2 1]A six-stage, automatic firing mechanism. For Aigis.[n][e]

[msg Item_0B2]
[f 0 5 65278][f 2 1]An 80mm caliber grenade launcher. For Aigis.[n][e]

[msg Item_0B3]
[f 0 5 65278][f 2 1]A rifle that fires bullets powered by orgone energy. For Aigis.[n][e]

[msg Item_0B4]
[f 0 5 65278][f 2 1]A cannon infused with the essence of fallen tears. For Aigis.[n][e]

[msg Item_0B5]
[f 0 5 65278][f 2 1]A cannon with a uniquely long barrel. For Aigis.[n][e]

[msg Item_0B6]
[f 0 5 65278][f 2 1]A cannon that embodies the sigh of a sinner, head hung low. For Aigis.[n][e]

[msg Item_0B7]
[f 0 5 65278][f 2 1]A cannon that uses electromagnetism to fire iron slugs. For Aigis.[n][e]

[msg Item_0B8]
[f 0 5 65278][f 2 1]A cannon harboring the rage of one who fell into madness. For Aigis.[n][e]

[msg Item_0B9]
[f 0 5 65278][f 2 1]A weapon that fires iron fists, like something out of a robot anime.[n][e]

[msg Item_0BA]
[f 0 5 65278][f 2 1]The latest model of anti-Shadow rifle. For Aigis.[n][e]

[msg Item_0BB]
[f 0 5 65278][f 2 1]A cannon made of frozen tears. For Aigis.[n][e]

[msg Item_0BC]
[f 0 5 65278][f 2 1]A cannon of beautiful and radiant power. For Aigis.[n][e]

[msg Item_0BD]
[f 0 5 65278][f 2 1]A firearm that is said to burn away impurity. For Aigis.[n][e]

[msg Item_0BE]
[f 0 5 65278][f 2 1]A cannon that generates annihilation between particles. For Aigis.[n][e]

[msg Item_0BF]
[f 0 5 65278][f 2 1]A sacred gun that reduces the HP cost of physical skills by half. For Aigis.[n][e]

[msg Item_0C0]
[f 0 5 65278][f 2 1]A grenade launcher that fires flash grenades. For Aigis.[n][e]

[msg Item_0C1]
[f 0 5 65278][f 2 1]A firearm with power like a kiss from a god. For Aigis.[n][e]

[msg Item_0C2]
[f 0 5 65278][f 2 1]A cannon of twisted and distorted power. For Aigis.[n][e]

[msg Item_0C3]
[f 0 5 65278][f 2 1]A firearm that shoots special rounds with high force of impact. For Aigis.[n][e]

[msg Item_0C4]
[f 0 5 65278][f 2 1]A robust firearm that shoots through resistances. For Aigis.[n][e]

[msg Item_0C5]
[f 0 5 65278][f 2 1]A fusion gun that has no quirks and is easy to use. For Aigis.[n][e]

[msg Item_0C6]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0C7]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0C8]
[f 0 5 65278][f 2 1]A gun that temporarily boosts Accuracy/Evasion of all allies. For Aigis.[n][e]

[msg Item_0C9]
[f 0 5 65278][f 2 1]A sharp knife designed for fighting Shadows.[n][e]

[msg Item_0CA]
[f 0 5 65278][f 2 1]A bone full of calcium that provides strength to those who chew it.[n][e]

[msg Item_0CB]
[f 0 5 65278][f 2 1]A well-polished kunai. For Koromaru.[n][e]

[msg Item_0CC]
[f 0 5 65278][f 2 1]A knife that is said to bring good fortune. For Koromaru.[n][e]

[msg Item_0CD]
[f 0 5 65278][f 2 1]A lethal blade shaped like a crescent moon. For Koromaru.[n][e]

[msg Item_0CE]
[f 0 5 65278][f 2 1]A knife that embodies the sigh of a sinner, head hung low. For Koromaru.[n][e]

[msg Item_0CF]
[f 0 5 65278][f 2 1]A knife used to break swords. For Koromaru.[n][e]

[msg Item_0D0]
[f 0 5 65278][f 2 1]A knife harboring the rage of one who fell into madness. For Koromaru.[n][e]

[msg Item_0D1]
[f 0 5 65278][f 2 1]A kunai that was favored by a certain ninja. For Koromaru.[n][e]

[msg Item_0D2]
[f 0 5 65278][f 2 1]A knife made of frozen tears. For Koromaru.[n][e]

[msg Item_0D3]
[f 0 5 65278][f 2 1]A blade as powerful as a fierce howl. For Koromaru.[n][e]

[msg Item_0D4]
[f 0 5 65278][f 2 1]A thick, heavy knife. For Koromaru.[n][e]

[msg Item_0D5]
[f 0 5 65278][f 2 1]A knife of beautiful and radiant power. For Koromaru.[n][e]

[msg Item_0D6]
[f 0 5 65278][f 2 1]Raises Attack when on the receiving end of a Shift. For Koromaru.[n][e]

[msg Item_0D7]
[f 0 5 65278][f 2 1]A tool that halves the hit rate of incoming attacks. For Koromaru.[n][e]

[msg Item_0D8]
[f 0 5 65278][f 2 1]A fusion blade that strengthens Dark attacks. For Koromaru.[n][e]

[msg Item_0D9]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0DA]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0DB]
[f 0 5 65278][f 2 1]A knife infused with the essence of fallen tears. For Koromaru.[n][e]

[msg Item_0DC]
[f 0 5 65278][f 2 1]A knife of twisted and distorted power. For Koromaru.[n][e]

[msg Item_0DD]
[f 0 5 65278][f 2 1]A knife polished so thoroughly that it shines. For Koromaru.[n][e]

[msg Item_0DE]
[f 0 5 65278][f 2 1]A kunai that changes attack affinity to Dark. For Koromaru.[n][e]

[msg Item_0DF]
[f 0 5 65278][f 2 1]A blade that changes attack affinity to Wind. For Koromaru.[n][e]

[msg Item_0E0]
[f 0 5 65278][f 2 1]A knife with thorough slicing ability. Should not be pointed at people.[n][e]

[msg Item_0E1]
[f 0 5 65278][f 2 1]A demonic knife that strengthens Dark attacks. For Koromaru.[n][e]

[msg Item_0E2]
[f 0 5 65278][f 2 1]An easy-to-use long spear designed for fighting Shadows.[n][e]

[msg Item_0E3]
[f 0 5 65278][f 2 1]A magical spear that temporarily boosts Attack. For Amada.[n][e]

[msg Item_0E4]
[f 0 5 65278][f 2 1]A long-handled weapon used during Europe's middle ages. For Amada.[n][e]

[msg Item_0E5]
[f 0 5 65278][f 2 1]A spear infused with the essence of fallen tears. For Amada.[n][e]

[msg Item_0E6]
[f 0 5 65278][f 2 1]A long spear that was used by a legendary king. For Amada.[n][e]

[msg Item_0E7]
[f 0 5 65278][f 2 1]A spear that embodies the sigh of a sinner, head hung low. For Amada.[n][e]

[msg Item_0E8]
[f 0 5 65278][f 2 1]A common brush used for cleaning. Can also clean the area of Shadows.[n][e]

[msg Item_0E9]
[f 0 5 65278][f 2 1]A long spear with superb piercing power. For Amada.[n][e]

[msg Item_0EA]
[f 0 5 65278][f 2 1]A spear harboring the rage of one who fell into madness. For Amada.[n][e]

[msg Item_0EB]
[f 0 5 65278][f 2 1]A renowned spear that is long and beautiful. For Amada.[n][e]

[msg Item_0EC]
[f 0 5 65278][f 2 1]A long-handled weapon with a simple shape. For Amada.[n][e]

[msg Item_0ED]
[f 0 5 65278][f 2 1]A spear made of frozen tears. For Amada.[n][e]

[msg Item_0EE]
[f 0 5 65278][f 2 1]A long spear made in the Muromachi period. For Amada.[n][e]

[msg Item_0EF]
[f 0 5 65278][f 2 1]A spear of beautiful and radiant power. For Amada.[n][e]

[msg Item_0F0]
[f 0 5 65278][f 2 1]A spear that protects the user from mental ailments. For Amada.[n][e]

[msg Item_0F1]
[f 0 5 65278][f 2 1]A magical spear that changes attack affinity to Light. For Amada.[n][e]

[msg Item_0F2]
[f 0 5 65278][f 2 1]A silver spear that changes attack affinity to Electric. For Amada.[n][e]

[msg Item_0F3]
[f 0 5 65278][f 2 1]A trident imbued with the power of destruction and creation. For Amada.[n][e]

[msg Item_0F4]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0F5]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0F6]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_0F7]
[f 0 5 65278][f 2 1]A cross-shaped spear said to have belonged to royalty. For Amada.[n][e]

[msg Item_0F8]
[f 0 5 65278][f 2 1]A spear of twisted and distorted power. For Amada.[n][e]

[msg Item_0F9]
[f 0 5 65278][f 2 1]A mystical spear that grants its user magical powers. For Amada.[n][e]

[msg Item_0FA]
[f 0 5 65278][f 2 1]A ceremonial lance that changes attack affinity to Light. For Amada.[n][e]

[msg Item_0FB]
[f 0 5 65278][f 2 1]A destructive battle-axe designed for fighting Shadows.[n][e]

[msg Item_0FC]
[f 0 5 65278][f 2 1]A giant hammer that emits a ferocious aura. For Aragaki.[n][e]

[msg Item_0FD]
[f 0 5 65278][f 2 1]A dangerous cudgel made by a psychopathic murderer. For Aragaki.[n][e]

[msg Item_0FE]
[f 0 5 65278][f 2 1]It says, "Front of School." It should probably be returned someday.[n][e]

[msg Item_0FF]
[f 0 5 65278][f 2 1]A giant axe that was used for executions. For Aragaki.[n][e]

[msg Item_100]
[f 0 5 65278][f 2 1]A rod that boasts significant strength. For Aragaki.[n][e]

[msg Item_101]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_102]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_103]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_104]
[f 0 5 65278][f 2 1]Temporarily boosts the user's critical rate. For Aragaki.[n][e]

[msg Item_105]
[f 0 5 65278][f 2 1]A giant hammer blessed by the god of earth. For Aragaki.[n][e]

[msg Item_106]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_107]
[f 0 5 65278][f 2 1]A battle-axe that strengthens Strike attacks. For Aragaki.[n][e]

[msg Item_108]
[f 0 5 65278][f 2 1]A large, metal hammer that can shatter the ground. For Aragaki.[n][e]

[msg Item_109]
[f 0 5 65278][f 2 1]A sacred hammer that changes attack affinity to Electric. For Aragaki.[n][e]

[msg Item_10A]
[f 0 5 65278][f 2 1]A staff that strengthens the first physical attack of each battle. For Aragaki.[n][e]

[msg Item_10B]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_10C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_10D]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_10E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_10F]
[f 0 5 65278][f 2 1]User recovers SP when on the receiving end of a Shift. For Amada.[n][e]

[msg Item_110]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_111]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_112]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_113]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_114]
[f 0 5 65278][f 2 1]Nothing is equipped.[n][e]

[msg Item_115]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_116]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_117]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_118]
[f 0 5 65278][f 2 1]A sharp one-handed sword designed for fighting Shadows.[n][e]

[msg Item_119]
[f 0 5 65278][f 2 1]A powerful longbow designed for fighting Shadows.[n][e]

[msg Item_11A]
[f 0 5 65278][f 2 1]A long, heavy great sword designed for fighting Shadows.[n][e]

[msg Item_11B]
[f 0 5 65278][f 2 1]Tough weaponized gloves designed for fighting Shadows.[n][e]

[msg Item_11C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_11D]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_11E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_11F]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_120]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_121]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_122]
[f 0 5 65278][f 2 1]A sword that changes attack affinity to Dark. For [f 4 2].[n][e]

[msg Item_123]
[f 0 5 65278][f 2 1]This sword of legend... is a fake. The anger of being tricked turns into power.[n][e]

[msg Item_124]
[f 0 5 65278][f 2 1]Medium likelihood to Repel physical attacks. For [f 4 2].[n][e]

[msg Item_125]
[f 0 5 65278][f 2 1]A cursed sword seeped in blood. For [f 4 2].[n][e]

[msg Item_126]
[f 0 5 65278][f 2 1]A sword that changes attack affinity to Light. For [f 4 2].[n][e]

[msg Item_127]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_128]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_129]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_12A]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_12B]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_12C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_12D]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_12E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_12F]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_130]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_131]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_132]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_133]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_134]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_135]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_136]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_137]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_138]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_139]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_13A]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_13B]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_13C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_13D]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_13E]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_13F]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_140]
[f 0 5 65278][f 2 1]A striking weapon with a cruciform tip. For Metis.[n][e]

[msg Item_141]
[f 0 5 65278][f 2 1]A destructive battle-axe designed for fighting Shadows.[n][e]

[msg Item_142]
[f 0 5 65278][f 2 1]A giant hammer that emits a ferocious aura. For Metis.[n][e]

[msg Item_143]
[f 0 5 65278][f 2 1]An axe infused with the essence of fallen tears. For Metis.[n][e]

[msg Item_144]
[f 0 5 65278][f 2 1]It says, "Front of School." It should probably be returned someday.[n][e]

[msg Item_145]
[f 0 5 65278][f 2 1]A giant axe that was used for executions. For Metis.[n][e]

[msg Item_146]
[f 0 5 65278][f 2 1]An axe that embodies the sigh of a sinner, head hung low. For Metis.[n][e]

[msg Item_147]
[f 0 5 65278][f 2 1]Temporarily boosts the user's critical rate. For Metis.[n][e]

[msg Item_148]
[f 0 5 65278][f 2 1]A giant hammer blessed by the god of earth. For Metis.[n][e]

[msg Item_149]
[f 0 5 65278][f 2 1]A battle-axe that strengthens Strike attacks. For Metis.[n][e]

[msg Item_14A]
[f 0 5 65278][f 2 1]A large, metal hammer that can shatter the ground. For Metis.[n][e]

[msg Item_14B]
[f 0 5 65278][f 2 1]A sacred hammer that changes attack affinity to Electric. For Metis.[n][e]

[msg Item_14C]
[f 0 5 65278][f 2 1]A staff that strengthens the first physical attack of each battle. For Metis.[n][e]

[msg Item_14D]
[f 0 5 65278][f 2 1]A versatile poleaxe for numerous destructive uses. For Metis.[n][e]

[msg Item_14E]
[f 0 5 65278][f 2 1]A brutal cudgel a demon might wield. For Metis.[n][e]

[msg Item_14F]
[f 0 5 65278][f 2 1]An axe harboring the rage of one who fell into madness. For Metis.[n][e]

[msg Item_150]
[f 0 5 65278][f 2 1]An axe that raises Attack when on the receiving end of a Shift. For Metis.[n][e]

[msg Item_151]
[f 0 5 65278][f 2 1]A club with a metal slab on one end. For Metis.[n][e]

[msg Item_152]
[f 0 5 65278][f 2 1]A jet-propelled hammer that raises Attack at the start of battle. For Metis.[n][e]

[msg Item_153]
[f 0 5 65278][f 2 1]An axe made of frozen tears. For Metis.[n][e]

[msg Item_154]
[f 0 5 65278][f 2 1]A club with myriad obsidian blades adorning its edges. For Metis.[n][e]

[msg Item_155]
[f 0 5 65278][f 2 1]An axe of twisted and distorted power. For Metis.[n][e]

[msg Item_156]
[f 0 5 65278][f 2 1]An axe of beautiful and radiant power. For Metis.[n][e]

[msg Item_157]
[f 0 5 65278][f 2 1]A staff harboring mystical power. For Metis.[n][e]

[msg Item_158]
[f 0 5 65278][f 2 1]A godly hammer that smashes through resistances. For Metis.[n][e]

[msg Item_159]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_15A]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_15B]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_15C]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_15D]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_15E]
[f 0 5 65278][f 2 1]A bow infused with the essence of fallen tears. For Yukari.[n][e]

[msg Item_15F]
[f 0 5 65278][f 2 1]A bow infused with the essence of fallen tears. For Yukari.[n][e]

[msg Item_160]
[f 0 5 65278][f 2 1]A bow that embodies the sigh of a sinner, head hung low. For Yukari.[n][e]

[msg Item_161]
[f 0 5 65278][f 2 1]A bow that embodies the sigh of a sinner, head hung low. For Yukari.[n][e]

[msg Item_162]
[f 0 5 65278][f 2 1]A bow harboring the rage of one who fell into madness. For Yukari.[n][e]

[msg Item_163]
[f 0 5 65278][f 2 1]A bow harboring the rage of one who fell into madness. For Yukari.[n][e]

[msg Item_164]
[f 0 5 65278][f 2 1]A bow harboring the rage of one who fell into madness. For Yukari.[n][e]

[msg Item_165]
[f 0 5 65278][f 2 1]A bow made of frozen tears. For Yukari.[n][e]

[msg Item_166]
[f 0 5 65278][f 2 1]A bow made of frozen tears. For Yukari.[n][e]

[msg Item_167]
[f 0 5 65278][f 2 1]A bow made of frozen tears. For Yukari.[n][e]

[msg Item_168]
[f 0 5 65278][f 2 1]A bow of twisted and distorted power. For Yukari.[n][e]

[msg Item_169]
[f 0 5 65278][f 2 1]A bow of twisted and distorted power. For Yukari.[n][e]

[msg Item_16A]
[f 0 5 65278][f 2 1]A bow of twisted and distorted power. For Yukari.[n][e]

[msg Item_16B]
[f 0 5 65278][f 2 1]A bow of beautiful and radiant power. For Yukari.[n][e]

[msg Item_16C]
[f 0 5 65278][f 2 1]A bow of beautiful and radiant power. For Yukari.[n][e]

[msg Item_16D]
[f 0 5 65278][f 2 1]A bow of beautiful and radiant power. For Yukari.[n][e]

[msg Item_16E]
[f 0 5 65278][f 2 1]A sword infused with the essence of fallen tears. For Junpei.[n][e]

[msg Item_16F]
[f 0 5 65278][f 2 1]A sword infused with the essence of fallen tears. For Junpei.[n][e]

[msg Item_170]
[f 0 5 65278][f 2 1]A sword that embodies the sigh of a sinner, head hung low. For Junpei.[n][e]

[msg Item_171]
[f 0 5 65278][f 2 1]A sword that embodies the sigh of a sinner, head hung low. For Junpei.[n][e]

[msg Item_172]
[f 0 5 65278][f 2 1]A sword harboring the rage of one who fell into madness. For Junpei.[n][e]

[msg Item_173]
[f 0 5 65278][f 2 1]A sword harboring the rage of one who fell into madness. For Junpei.[n][e]

[msg Item_174]
[f 0 5 65278][f 2 1]A sword harboring the rage of one who fell into madness. For Junpei.[n][e]

[msg Item_175]
[f 0 5 65278][f 2 1]A sword made of frozen tears. For Junpei.[n][e]

[msg Item_176]
[f 0 5 65278][f 2 1]A sword made of frozen tears. For Junpei.[n][e]

[msg Item_177]
[f 0 5 65278][f 2 1]A sword made of frozen tears. For Junpei.[n][e]

[msg Item_178]
[f 0 5 65278][f 2 1]A sword of twisted and distorted power. For Junpei.[n][e]

[msg Item_179]
[f 0 5 65278][f 2 1]A sword of twisted and distorted power. For Junpei.[n][e]

[msg Item_17A]
[f 0 5 65278][f 2 1]A sword of twisted and distorted power. For Junpei.[n][e]

[msg Item_17B]
[f 0 5 65278][f 2 1]A sword of beautiful and radiant power. For Junpei.[n][e]

[msg Item_17C]
[f 0 5 65278][f 2 1]A sword of beautiful and radiant power. For Junpei.[n][e]

[msg Item_17D]
[f 0 5 65278][f 2 1]A sword of beautiful and radiant power. For Junpei.[n][e]

[msg Item_17E]
[f 0 5 65278][f 2 1]Gloves infused with the essence of fallen tears. For Sanada.[n][e]

[msg Item_17F]
[f 0 5 65278][f 2 1]Gloves infused with the essence of fallen tears. For Sanada.[n][e]

[msg Item_180]
[f 0 5 65278][f 2 1]Gloves that embody the sigh of a sinner, head hung low. For Sanada.[n][e]

[msg Item_181]
[f 0 5 65278][f 2 1]Gloves that embody the sigh of a sinner, head hung low. For Sanada.[n][e]

[msg Item_182]
[f 0 5 65278][f 2 1]Gloves harboring the rage of one who fell into madness. For Sanada.[n][e]

[msg Item_183]
[f 0 5 65278][f 2 1]Gloves harboring the rage of one who fell into madness. For Sanada.[n][e]

[msg Item_184]
[f 0 5 65278][f 2 1]Gloves harboring the rage of one who fell into madness. For Sanada.[n][e]

[msg Item_185]
[f 0 5 65278][f 2 1]Gloves made of frozen tears. For Sanada.[n][e]

[msg Item_186]
[f 0 5 65278][f 2 1]Gloves made of frozen tears. For Sanada.[n][e]

[msg Item_187]
[f 0 5 65278][f 2 1]Gloves made of frozen tears. For Sanada.[n][e]

[msg Item_188]
[f 0 5 65278][f 2 1]Gloves of twisted and distorted power. For Sanada.[n][e]

[msg Item_189]
[f 0 5 65278][f 2 1]Gloves of twisted and distorted power. For Sanada.[n][e]

[msg Item_18A]
[f 0 5 65278][f 2 1]Gloves of twisted and distorted power. For Sanada.[n][e]

[msg Item_18B]
[f 0 5 65278][f 2 1]Gloves of beautiful and radiant power. For Sanada.[n][e]

[msg Item_18C]
[f 0 5 65278][f 2 1]Gloves of beautiful and radiant power. For Sanada.[n][e]

[msg Item_18D]
[f 0 5 65278][f 2 1]Gloves of beautiful and radiant power. For Sanada.[n][e]

[msg Item_18E]
[f 0 5 65278][f 2 1]A rapier infused with the essence of fallen tears. For Mitsuru.[n][e]

[msg Item_18F]
[f 0 5 65278][f 2 1]A rapier infused with the essence of fallen tears. For Mitsuru.[n][e]

[msg Item_190]
[f 0 5 65278][f 2 1]A rapier that embodies the sigh of a sinner, head hung low. For Mitsuru.[n][e]

[msg Item_191]
[f 0 5 65278][f 2 1]A rapier that embodies the sigh of a sinner, head hung low. For Mitsuru.[n][e]

[msg Item_192]
[f 0 5 65278][f 2 1]A rapier harboring the rage of one who fell into madness. For Mitsuru.[n][e]

[msg Item_193]
[f 0 5 65278][f 2 1]A rapier harboring the rage of one who fell into madness. For Mitsuru.[n][e]

[msg Item_194]
[f 0 5 65278][f 2 1]A rapier harboring the rage of one who fell into madness. For Mitsuru.[n][e]

[msg Item_195]
[f 0 5 65278][f 2 1]A rapier made of frozen tears. For Mitsuru.[n][e]

[msg Item_196]
[f 0 5 65278][f 2 1]A rapier made of frozen tears. For Mitsuru.[n][e]

[msg Item_197]
[f 0 5 65278][f 2 1]A rapier made of frozen tears. For Mitsuru.[n][e]

[msg Item_198]
[f 0 5 65278][f 2 1]A rapier of twisted and distorted power. For Mitsuru.[n][e]

[msg Item_199]
[f 0 5 65278][f 2 1]A rapier of twisted and distorted power. For Mitsuru.[n][e]

[msg Item_19A]
[f 0 5 65278][f 2 1]A rapier of twisted and distorted power. For Mitsuru.[n][e]

[msg Item_19B]
[f 0 5 65278][f 2 1]A rapier of beautiful and radiant power. For Mitsuru.[n][e]

[msg Item_19C]
[f 0 5 65278][f 2 1]A rapier of beautiful and radiant power. For Mitsuru.[n][e]

[msg Item_19D]
[f 0 5 65278][f 2 1]A rapier of beautiful and radiant power. For Mitsuru.[n][e]

[msg Item_19E]
[f 0 5 65278][f 2 1]A cannon infused with the essence of fallen tears. For Aigis.[n][e]

[msg Item_19F]
[f 0 5 65278][f 2 1]A cannon infused with the essence of fallen tears. For Aigis.[n][e]

[msg Item_1A0]
[f 0 5 65278][f 2 1]A cannon that embodies the sigh of a sinner, head hung low. For Aigis.[n][e]

[msg Item_1A1]
[f 0 5 65278][f 2 1]A cannon that embodies the sigh of a sinner, head hung low. For Aigis.[n][e]

[msg Item_1A2]
[f 0 5 65278][f 2 1]A cannon harboring the rage of one who fell into madness. For Aigis.[n][e]

[msg Item_1A3]
[f 0 5 65278][f 2 1]A cannon harboring the rage of one who fell into madness. For Aigis.[n][e]

[msg Item_1A4]
[f 0 5 65278][f 2 1]A cannon harboring the rage of one who fell into madness. For Aigis.[n][e]

[msg Item_1A5]
[f 0 5 65278][f 2 1]A cannon made of frozen tears. For Aigis.[n][e]

[msg Item_1A6]
[f 0 5 65278][f 2 1]A cannon made of frozen tears. For Aigis.[n][e]

[msg Item_1A7]
[f 0 5 65278][f 2 1]A cannon made of frozen tears. For Aigis.[n][e]

[msg Item_1A8]
[f 0 5 65278][f 2 1]A cannon of twisted and distorted power. For Aigis.[n][e]

[msg Item_1A9]
[f 0 5 65278][f 2 1]A cannon of twisted and distorted power. For Aigis.[n][e]

[msg Item_1AA]
[f 0 5 65278][f 2 1]A cannon of twisted and distorted power. For Aigis.[n][e]

[msg Item_1AB]
[f 0 5 65278][f 2 1]A cannon of beautiful and radiant power. For Aigis.[n][e]

[msg Item_1AC]
[f 0 5 65278][f 2 1]A cannon of beautiful and radiant power. For Aigis.[n][e]

[msg Item_1AD]
[f 0 5 65278][f 2 1]A cannon of beautiful and radiant power. For Aigis.[n][e]

[msg Item_1AE]
[f 0 5 65278][f 2 1]A knife infused with the essence of fallen tears. For Koromaru.[n][e]

[msg Item_1AF]
[f 0 5 65278][f 2 1]A knife infused with the essence of fallen tears. For Koromaru.[n][e]

[msg Item_1B0]
[f 0 5 65278][f 2 1]A knife that embodies the sigh of a sinner, head hung low. For Koromaru.[n][e]

[msg Item_1B1]
[f 0 5 65278][f 2 1]A knife that embodies the sigh of a sinner, head hung low. For Koromaru.[n][e]

[msg Item_1B2]
[f 0 5 65278][f 2 1]A knife harboring the rage of one who fell into madness. For Koromaru.[n][e]

[msg Item_1B3]
[f 0 5 65278][f 2 1]A knife harboring the rage of one who fell into madness. For Koromaru.[n][e]

[msg Item_1B4]
[f 0 5 65278][f 2 1]A knife harboring the rage of one who fell into madness. For Koromaru.[n][e]

[msg Item_1B5]
[f 0 5 65278][f 2 1]A knife made of frozen tears. For Koromaru.[n][e]

[msg Item_1B6]
[f 0 5 65278][f 2 1]A knife made of frozen tears. For Koromaru.[n][e]

[msg Item_1B7]
[f 0 5 65278][f 2 1]A knife made of frozen tears. For Koromaru.[n][e]

[msg Item_1B8]
[f 0 5 65278][f 2 1]A knife of twisted and distorted power. For Koromaru.[n][e]

[msg Item_1B9]
[f 0 5 65278][f 2 1]A knife of twisted and distorted power. For Koromaru.[n][e]

[msg Item_1BA]
[f 0 5 65278][f 2 1]A knife of twisted and distorted power. For Koromaru.[n][e]

[msg Item_1BB]
[f 0 5 65278][f 2 1]A knife of beautiful and radiant power. For Koromaru.[n][e]

[msg Item_1BC]
[f 0 5 65278][f 2 1]A knife of beautiful and radiant power. For Koromaru.[n][e]

[msg Item_1BD]
[f 0 5 65278][f 2 1]A knife of beautiful and radiant power. For Koromaru.[n][e]

[msg Item_1BE]
[f 0 5 65278][f 2 1]A spear infused with the essence of fallen tears. For Amada.[n][e]

[msg Item_1BF]
[f 0 5 65278][f 2 1]A spear infused with the essence of fallen tears. For Amada.[n][e]

[msg Item_1C0]
[f 0 5 65278][f 2 1]A spear that embodies the sigh of a sinner, head hung low. For Amada.[n][e]

[msg Item_1C1]
[f 0 5 65278][f 2 1]A spear that embodies the sigh of a sinner, head hung low. For Amada.[n][e]

[msg Item_1C2]
[f 0 5 65278][f 2 1]A spear harboring the rage of one who fell into madness. For Amada.[n][e]

[msg Item_1C3]
[f 0 5 65278][f 2 1]A spear harboring the rage of one who fell into madness. For Amada.[n][e]

[msg Item_1C4]
[f 0 5 65278][f 2 1]A spear harboring the rage of one who fell into madness. For Amada.[n][e]

[msg Item_1C5]
[f 0 5 65278][f 2 1]A spear made of frozen tears. For Amada.[n][e]

[msg Item_1C6]
[f 0 5 65278][f 2 1]A spear made of frozen tears. For Amada.[n][e]

[msg Item_1C7]
[f 0 5 65278][f 2 1]A spear made of frozen tears. For Amada.[n][e]

[msg Item_1C8]
[f 0 5 65278][f 2 1]A spear of twisted and distorted power. For Amada.[n][e]

[msg Item_1C9]
[f 0 5 65278][f 2 1]A spear of twisted and distorted power. For Amada.[n][e]

[msg Item_1CA]
[f 0 5 65278][f 2 1]A spear of twisted and distorted power. For Amada.[n][e]

[msg Item_1CB]
[f 0 5 65278][f 2 1]A spear of beautiful and radiant power. For Amada.[n][e]

[msg Item_1CC]
[f 0 5 65278][f 2 1]A spear of beautiful and radiant power. For Amada.[n][e]

[msg Item_1CD]
[f 0 5 65278][f 2 1]A spear of beautiful and radiant power. For Amada.[n][e]

[msg Item_1CE]
[f 0 5 65278][f 2 1]An axe infused with the essence of fallen tears. For Metis.[n][e]

[msg Item_1CF]
[f 0 5 65278][f 2 1]An axe infused with the essence of fallen tears. For Metis.[n][e]

[msg Item_1D0]
[f 0 5 65278][f 2 1]An axe that embodies the sigh of a sinner, head hung low. For Metis.[n][e]

[msg Item_1D1]
[f 0 5 65278][f 2 1]An axe that embodies the sigh of a sinner, head hung low. For Metis.[n][e]

[msg Item_1D2]
[f 0 5 65278][f 2 1]An axe harboring the rage of one who fell into madness. For Metis.[n][e]

[msg Item_1D3]
[f 0 5 65278][f 2 1]An axe harboring the rage of one who fell into madness. For Metis.[n][e]

[msg Item_1D4]
[f 0 5 65278][f 2 1]An axe harboring the rage of one who fell into madness. For Metis.[n][e]

[msg Item_1D5]
[f 0 5 65278][f 2 1]An axe made of frozen tears. For Metis.[n][e]

[msg Item_1D6]
[f 0 5 65278][f 2 1]An axe made of frozen tears. For Metis.[n][e]

[msg Item_1D7]
[f 0 5 65278][f 2 1]An axe made of frozen tears. For Metis.[n][e]

[msg Item_1D8]
[f 0 5 65278][f 2 1]An axe of twisted and distorted power. For Metis.[n][e]

[msg Item_1D9]
[f 0 5 65278][f 2 1]An axe of twisted and distorted power. For Metis.[n][e]

[msg Item_1DA]
[f 0 5 65278][f 2 1]An axe of twisted and distorted power. For Metis.[n][e]

[msg Item_1DB]
[f 0 5 65278][f 2 1]An axe of beautiful and radiant power. For Metis.[n][e]

[msg Item_1DC]
[f 0 5 65278][f 2 1]An axe of beautiful and radiant power. For Metis.[n][e]

[msg Item_1DD]
[f 0 5 65278][f 2 1]An axe of beautiful and radiant power. For Metis.[n][e]

[msg Item_1DE]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1DF]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E0]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E1]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E2]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E3]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E4]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E5]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E6]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E7]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E8]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1E9]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1EA]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1EB]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1EC]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1ED]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1EE]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1EF]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F0]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F1]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F2]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F3]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F4]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F5]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F6]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F7]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F8]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1F9]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1FA]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1FB]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1FC]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1FD]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1FE]
[f 0 5 65278][f 2 1]未使用[n][e]

[msg Item_1FF]
[f 0 5 65278][f 2 1]未使用[n][e]

